1
1
1
1
1
error: terminating connection due to administrator command
    at Connection.parseE (/Users/tcolar/code/convoy/ormtest/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/tcolar/code/convoy/ormtest/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/tcolar/code/convoy/ormtest/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17) {
  name: 'error',
  length: 116,
  severity: 'FATAL',
  code: '57P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '2913',
  routine: 'ProcessInterrupts',
  client: Client {
    _events: [Object: null prototype] { error: [Function] },
    _eventsCount: 1,
    _maxListeners: undefined,
    connectionParameters: ConnectionParameters {
      user: 'donvoy',
      database: 'work_queue_dev',
      port: 5499,
      host: '127.0.0.1',
      password: null,
      binary: false,
      ssl: false,
      client_encoding: '',
      replication: undefined,
      isDomainSocket: false,
      application_name: 'test',
      fallback_application_name: undefined,
      statement_timeout: false,
      query_timeout: false,
      connect_timeout: 0
    },
    user: 'donvoy',
    database: 'work_queue_dev',
    port: 5499,
    host: '127.0.0.1',
    password: null,
    replication: undefined,
    _Promise: [Function: Promise] {
      TypeError: [Function: TypeError],
      RangeError: [Function: RangeError],
      CancellationError: [Function: SubError],
      TimeoutError: [Function: SubError],
      OperationalError: [Function: OperationalError],
      RejectionError: [Function: OperationalError],
      AggregateError: [Function: SubError],
      _peekContext: [Function: peekContext],
      onPossiblyUnhandledRejection: [Function],
      onUnhandledRejectionHandled: [Function],
      longStackTraces: [Function],
      hasLongStackTraces: [Function],
      config: [Function],
      getNewLibraryCopy: [Function],
      is: [Function],
      fromCallback: [Function],
      fromNode: [Function],
      all: [Function],
      cast: [Function],
      fulfilled: [Function],
      resolve: [Function],
      rejected: [Function],
      reject: [Function],
      setScheduler: [Function],
      pending: [Function],
      defer: [Function],
      method: [Function],
      try: [Function],
      attempt: [Function],
      bind: [Function],
      PromiseInspection: [Function: PromiseInspection],
      join: [Function],
      Promise: [Circular],
      version: '3.5.5',
      coroutine: [Function],
      spawn: [Function],
      map: [Function],
      promisify: [Function],
      promisifyAll: [Function],
      props: [Function],
      race: [Function],
      reduce: [Function],
      settle: [Function],
      some: [Function],
      _SomePromiseArray: [Function: SomePromiseArray],
      delay: [Function],
      using: [Function],
      any: [Function],
      each: [Function],
      mapSeries: [Function: PromiseMapSeries],
      filter: [Function],
      noConflict: [Function: noConflict]
    },
    _types: TypeOverrides { _types: [Object], text: {}, binary: {} },
    _ending: true,
    _connecting: false,
    _connected: true,
    _connectionError: false,
    _queryable: false,
    connection: Connection {
      _events: [Object: null prototype],
      _eventsCount: 22,
      _maxListeners: undefined,
      stream: [Socket],
      _keepAlive: false,
      _keepAliveInitialDelayMillis: 0,
      lastBuffer: false,
      lastOffset: 0,
      buffer: null,
      offset: 112,
      encoding: 'utf8',
      parsedStatements: {},
      writer: [Object],
      ssl: false,
      _ending: true,
      _mode: 0,
      _emitMessage: false,
      _reader: [Object]
    },
    queryQueue: [],
    binary: false,
    processID: 31,
    secretKey: 215388114,
    ssl: false,
    _connectionTimeoutMillis: 0,
    release: [Function: bound release],
    activeQuery: null,
    readyForQuery: true,
    hasExecuted: true
  }
}
(node:53827) UnhandledPromiseRejectionWarning: Error: Client has encountered a connection error and is not queryable
    at /Users/tcolar/code/convoy/ormtest/node_modules/pg/lib/client.js:500:25
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
From previous event:
    at Client.query (/Users/tcolar/code/convoy/ormtest/node_modules/pg/lib/client.js:453:16)
    at /Users/tcolar/code/convoy/ormtest/dist/pgpool.js:63:49
    at step (/Users/tcolar/code/convoy/ormtest/dist/pgpool.js:33:23)
    at Object.next (/Users/tcolar/code/convoy/ormtest/dist/pgpool.js:14:53)
    at fulfilled (/Users/tcolar/code/convoy/ormtest/dist/pgpool.js:5:58)
(node:53827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:53827) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
‚ú®  Done in 18.72s.
‚ûú  ormtest git:(master) ‚úó yarn pool
yarn run v1.15.2
warning package.json: No license field
$ yarn install && tsc && node ./dist/pgpool.js
warning package.json: No license field
warning ormtest@1.0.0: No license field
[1/4] üîç  Resolving packages...
success Already up-to-date.
(node:53876) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5499
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
From previous event:
    at promisify (/Users/tcolar/code/convoy/ormtest/node_modules/pg-pool/index.js:61:18)
    at Pool.connect (/Users/tcolar/code/convoy/ormtest/node_modules/pg-pool/index.js:171:22)
    at /Users/tcolar/code/convoy/ormtest/dist/pgpool.js:56:49
    at step (/Users/tcolar/code/convoy/ormtest/dist/pgpool.js:33:23)
    at Object.next (/Users/tcolar/code/convoy/ormtest/dist/pgpool.js:14:53)
    at /Users/tcolar/code/convoy/ormtest/dist/pgpool.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tcolar/code/convoy/ormtest/dist/pgpool.js:4:12)
    at startWithPool (/Users/tcolar/code/convoy/ormtest/dist/pgpool.js:41:12)
    at Object.<anonymous> (/Users/tcolar/code/convoy/ormtest/dist/pgpool.js:79:6)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
(node:53876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:53876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
‚ú®  Done in 3.28s.
